version: '3'

volumes:
  node_modules:
  postgres:

services:
  app:
    image: node:16.13.2
    ports:
      - 3000:3000
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/node_modules
    working_dir: /workspace
    tty: true
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB} 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db:/workspace/db
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
